### PR TITLE
Fix #114 Only delete or add comment, not both

### LINKED ISSUE #114: Avoid duplicate comments on PRs
Whenever we detect that a linked issue is missing, we post a new comment. We shouldn't. We should only either have the comment or remove it, but never duplicate it

### PR DESCRIPTION
**Pull request by SRHerzog**
Fix #114

Edit: Rewrote branch and force pushed to fix line endings. Force push does not trigger the "synchronize" webhook that causes this action to run.

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Hard to review because there are too many whitespace changes. Can you please take a look? I know github supports ignoring them in the diffs, but something's off

**Comment by SRHerzog** [comment]
I had an OS configuration thing to sort out. I've got it fixed now.

**Review by simoneb — COMMENTED** [review]
I'm not sure I understand how this fixes the issue exactly, or more specifically, I do see how it addresses the issue by avoiding to write a comment if there is already one, but I think the existing code was not supposed to leave multiple comments on the issue already. That's because the `deleteLinkedIssueComments` function was being called unconditionally, and yet we saw issues with multiple comments on them.

Based on that, I believe that some code was already broken and while this change may prevent adding a comment if there is already one, I have a feeling that it may not be deleting the existing comment(s).

**Comment by SRHerzog** [comment]
I was unable to reproduce the issue where it would somehow leave multiple comments on the same PR, or find any examples. Can you share links to any PRs that demonstrate this behavior, or provide repro steps?

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
@SRHerzog I think I saw this behavior but now I cannot find a place where that happened. 

We still need to figure out why the build check is not running, see my earlier comment.

**Comment by simoneb** [comment]
@SRHerzog I think I saw this behavior but now I cannot find a place where that happened. 

We still need to figure out why the build check is not running, see my earlier comment.

**Pull request merged**
