### PR TITLE
Update docs with limitation

### LINKED ISSUE #33: Doesn't work for issues from other repositories
Gave this action a try in https://github.com/nearform/bench-template-mrm-preset/pull/1, and it doesn't seem like it works when referencing issues from other repositories.

### PR DESCRIPTION
**Pull request by sameer-coder**
This PR updates the docs with the limitation regarding referencing issues in another repository.

Closes #33

### CODE REVIEW

**Review by krisgrint — APPROVED** [review]

**Review by katafira — APPROVED** [review]
Looks good.

**Review by jhonrocha — APPROVED** [review]
LGTM

**Comment by sameer-coder** [comment]
@simoneb we can merge this one. I don't have permissions.

**Comment by simoneb** [comment]
now you can

**Pull request merged**
